version: "2"

run:
  timeout: 2m

linters-settings:
  revive:
    exclude:
      - test-package
      - package-comments
      - unnecessary-init
      - var-declaration
      - builtin-shadow
      - varnamelen
    rules:
      - name: varnamelen
        arguments: [1]

  wsl_v5:
    allow-first-in-block: true
    allow-whole-block: false
    branch-max-lines: 2

  depguard:
    list-type: allowlist
    include-go-root: true
    packages:
      - github.com/google/uuid
      - github.com/inovacc/config
      - github.com/inovacc/config/internal/viper
      - github.com/inovacc/config/internal/viper/internal
      - github.com/fsnotify/fsnotify
      - github.com/go-viper/mapstructure/v2
      - github.com/pelletier/go-toml/v2
      - github.com/sagikazarmark/locafero
      - github.com/spf13/afero
      - github.com/spf13/cast
      - github.com/spf13/pflag
      - github.com/stretchr/testify/assert
      - github.com/stretchr/testify/require
      - github.com/subosito/gotenv
      - gopkg.in/yaml.v3

linters:
  default: all
  enable:
    - govet
    - errcheck
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - dupl
    - errorlint
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    - gocyclo
    - godox
    - goprintffuncname
    - gosec
    - intrange
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - testifylint
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl_v5

  disable:
    - tagliatelle
    - gochecknoglobals
    - mnd
    - testpackage
    - varnamelen
    - paralleltest
    - gochecknoinits
    - funlen
    - wsl
    - cyclop
    - err113
    - errorlint
    - exhaustruct
    - forcetypeassert
    - funcorder
    - gocognit
    - godot
    - godox
    - gosec
    - gosmopolitan
    - intrange
    - ireturn
    - lll
    - nestif
    - nlreturn
    - noctx
    - noinlineerr
    - nonamedreturns
    - perfsprint
    - revive
    - tagalign
    - testifylint
    - thelper
    - usetesting
    - wrapcheck
    - depguard
    - dupl
    - goconst
    - gocyclo
    - whitespace
    - wsl_v5
